---
functional
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее. 
 - Пользователь должен иметь возможность продолжить просматривать каталог после добавления товара в корзину.
 - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. Корзина будет хранится в сессии браузера.
non-functional:
 - Сайт должен иметь адаптивную верстку
 - Сайт должен быть разработан как SPA-приложение, которое не перезагружает страницу
 - Сайт должен быть способен обрабатывать большое количество трафика
 - Сайт должен быть совместимым с последними версиями браузеров
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
implicit:
 - При смене языка сайт сохраняет свою адаптивность
 - При смене языка сайта, описание товара меняется в соответствии с выбранным языком
 - При смене языка на русский, валюта меняется на рубли, происходит корректная конвертация валют по текущему курсу
 - Для оплаты и доставки заказа на сайте существуют формы записи соответствующих данных, т.е. данные о способе оплаты, адрес и контактные данные
 - Перед указанием персональных данных появляется разрешение на обработку персональных данных
 - При открытии сайта открывается запрос на обработку cookie
 - На странице корзины пользователь имеет возможность очистить корзину полностью
 - На сайте все поля ввода защищены 
 - На сайте есть возможность обратной связи, обращения в поддержку
